spring:
  mail:
    host: smtp.gmail.com
    username: charity.01.app@gmail.com
    password: eftizsbosycugsav
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  jpa:
    hibernate:
      ddl-auto: update

# also available as db in cloud

#  datasource:
#    url: jdbc:mysql://charity-donation.cjtzmi22a08e.eu-north-1.rds.amazonaws.com/charity_donation?serverTimezone=UTC
#    username: admin
#    password: (paste when needed)

  datasource:
    url: jdbc:mysql://localhost:3306/charity_donation?serverTimezone=UTC
    username: root
    password: root

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  web:
    locale: pl_PL
    locale-resolver: fixed
  sql:
    init:
      mode: always


  logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR

  messages:
    basename: messages
    encoding: UTF-8

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 25

